name: "Native-Image"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-docker-image:
    name: Build native image in Docker

    runs-on: ubuntu-latest
    
    permissions:
      contents: read
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
